on:
  repository_dispatch:
    types: [trigger-app]
  workflow_dispatch:

permissions:
  contents: write
  pull-requests: write
  packages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          show-progress: false
          fetch-depth: 0

      - name: Run a one-line script
        run: |
          echo Hello, world!
          echo "${{ toJson(github.event.client_payload) }}" >> payload.txt

      - id: create_pull_request
        name: Create Pull Request
        uses: peter-evans/create-pull-request@v7
        with:
          title: "chore: Update JOOQ schema"
          commit-message: "chore: Update JOOQ schema"
          sign-commits: true
          branch: "chore/jooq-schema-update"
          branch-suffix: "short-commit-hash"
          draft: true

      - name: Run a one-line script
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
        run: |
          gh pr close ${{ steps.create_pull_request.outputs.pull-request-number }}
          gh pr reopen ${{ steps.create_pull_request.outputs.pull-request-number }}
